apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam
  namespace: sovereignbharat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
    spec:
      containers:
        - name: iam
          image: sovereignbharat/iam:latest
          ports:
            - containerPort: 8082
